# Generated by Django 2.0.4 on 2018-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('update_by', models.CharField(blank=True, editable=False, help_text='Last user who modified.', max_length=254, null=True, verbose_name='Update by')),
                ('error', models.TextField(blank=True, help_text='Detail about the error.', null=True, verbose_name='Error encountered')),
                ('message', models.TextField(blank=True, help_text='add additional information', null=True, verbose_name='Additional information')),
                ('name', models.CharField(help_text='Name of the category', max_length=254, verbose_name='Category name')),
                ('categories', models.ManyToManyField(blank=True, help_text='Sub categories', related_name='_category_categories_+', to='auctor.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
